server:
  port: 8888 #\u9879\u76EE\u542F\u52A8\u8BBF\u95EE\u7AEF\u53E3
spring:
  application:
    name: gods
  datasource: #\u8FDE\u63A5\u6570\u636E\u5E93\u914D\u7F6E
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima-estate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root #\u6570\u636E\u5E93\u7528\u6237
    password: 1234 #\u6570\u636E\u5E93\u5BC6\u7801\uFF0C\u9700\u8981\u6839\u636E\u5B9E\u9645\u60C5\u51B5\u8FDB\u884C\u586B\u5199
  servlet:
    multipart: #\u6587\u4EF6\u4E0A\u4F20\u914D\u7F6E
      max-file-size: 10MB
      max-request-size: 50MB
  main:
    allow-circular-references: true